CREATE TABLE UGYFEL_MASZKOLT (
    [LOGIN] VARCHAR(32) NOT NULL,
    EMAIL VARCHAR(64) MASKED WITH (FUNCTION = 'email()') NOT NULL,
    NEV VARCHAR(64) MASKED WITH (FUNCTION = 'partial(1,"*",0)') NOT NULL,
    SZULEV NUMERIC(4) MASKED WITH (FUNCTION = 'random(1900,2020)'),
    NEM CHAR(1),
    CIM VARCHAR(128)
);

INSERT INTO UGYFEL_MASZKOLT ([LOGIN], EMAIL, NEV, SZULEV, NEM, CIM)
SELECT [LOGIN], EMAIL, NEV, SZULEV, NEM, CIM FROM UGYFEL;

CREATE USER webshop_felhasznalo WITHOUT LOGIN;
GRANT SELECT ON UGYFEL_MASZKOLT TO webshop_felhasznalo

EXECUTE AS USER = 'webshop_felhasznalo'
SELECT * FROM UGYFEL_MASZKOLT
REVERT