SELECT sza.SZALLAS_NEV, szo.SZOBA_SZAMA, COUNT(f.FOGLALAS_PK) AS 'FOGLALASOK_SZAMA'
FROM Szoba szo JOIN Szallashely sza ON szo.SZALLAS_FK = sza.SZALLAS_ID
                LEFT JOIN Foglalas f ON szo.SZOBA_ID = f.SZOBA_FK
GROUP BY sza.SZALLAS_NEV, szo.SZOBA_SZAMA
HAVING COUNT(f.FOGLALAS_PK) <> 0